### ISSUE TITLE
Cannot connect to the Docker daemon (Concourse)

### ISSUE THREAD

**Issue by mlopez-eb** [karlkfi/concourse-dcind#6]
Hi Karlkfi,
I'm having issues using your image. Here is the error I'm receiving when running in Concourse:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

This is the build.yaml

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: karlkfi/concourse-dcind
    tag: latest

inputs:
  - name: pipeline_repo
  - name: src_repo
  - name: release_artifacts

outputs:
  - name: src_repo

params:
  dockerfile_location:
  svc_name:
#  git_comitt_sha:

run:
  path: pipeline_repo/tasks/docker/build.sh
```
It doesn't even have the chance to connect to Docker to run the commands in the build.sh.

Am I missing something? Is your entrypoint.sh required?

Thanks =]
